name: skill_swap
description: "SkillSwap is a vibrant platform that fosters skill exchange within local communities. Whether you're an expert in web design, cooking enthusiast, or DIY guru, SkillSwap connects you with others eager to exchange skills. Seamlessly browse, negotiate, and schedule skill exchanges with like-minded individuals, all while building a supportive community."
publish_to: 'none'
version: 0.0.8+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.3
  equatable: ^2.0.5
  path_provider: ^2.1.2
  flutter_displaymode: ^0.6.0
  easy_localization: ^3.0.3
  hive: ^2.2.3
  url_launcher: ^6.2.4
  fluentui_system_icons: ^1.1.225
  cloud_firestore: ^4.15.3
  firebase_auth: ^4.17.4
  font_awesome_flutter:
    git:
      url: git@github.com:nblauren/font_awesome_flutter.git
  get_it: ^7.6.7
  shared_preferences: ^2.2.2
  firebase_core: ^2.25.4
  flutter_facebook_auth: ^6.1.1
  sign_in_with_apple: ^5.0.0
  uni_links: ^0.5.1
  hexcolor: ^3.0.1
  google_sign_in: ^6.2.1
  formz: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1


flutter:
  uses-material-design: false

  assets:
    - assets/translations/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
