// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCunZD9wHCr4qn1l10syXvH0rYYqiAz3ys',
    appId: '1:93640063192:web:dc4f62dd2603cf8ced7fad',
    messagingSenderId: '93640063192',
    projectId: 'skillswap-e84de',
    authDomain: 'skillswap-e84de.firebaseapp.com',
    storageBucket: 'skillswap-e84de.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKLOuqHP4pS8f6GWHVK5t7YXcUCSu55Lw',
    appId: '1:93640063192:android:7563f4a7a44392f9ed7fad',
    messagingSenderId: '93640063192',
    projectId: 'skillswap-e84de',
    storageBucket: 'skillswap-e84de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCiTw98L7JlMm_AOU_tbVPCVlwsBQ-jf8',
    appId: '1:93640063192:ios:53dac4eb151e0a77ed7fad',
    messagingSenderId: '93640063192',
    projectId: 'skillswap-e84de',
    storageBucket: 'skillswap-e84de.appspot.com',
    iosBundleId: 'dev.feichtinger.flutterProductionBoilerplate',
  );
}
